site_name: Leafcloud Tutorials
nav:
    - Home: index.md
    - Setup secure instance access: 1-3-Set-up-secure-instance-access.md
    - Launching an instance: 2-3-Launching-an-instance.md
    - Cennecting to your instance: 3-3-Log-in-to-your-instance.md

theme: readthedocs
